services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__AppDbContext=Server=db;Database=AppDbContext;User Id=sa;Password=Your_password123;Encrypt=False
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - db
    # Remove external port mapping - backend will only be accessible internally
    expose:
      - "8080"
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
